### ISSUE TITLE
Club Hub Planning

### ISSUE THREAD

**Issue by magic005** [magic005/sprint4_frontend#1]
# Team Club Hub

Club Hub is a social media site targeted at making extracurricular opportunities at DNHS known and accessible, and offers a way to track those you currently take part in.

Frontend Repo: https://github.com/ThePencilSharpener/clubhub1frontend.git
Backend Repo: https://github.com/magic005/flocker_backend_CSP2.git

## Features to be added:
- Homepage to display "Your Clubs" & "Announcements"
- Gemini API integration for recommendations and chatting
- Chatrooms for each club
- Ability to add new clubs
- Cache user-inputted interests
- Activity recommendation system
- Member counts

## Pages & Functionality
- Home Page
  -  “Your Clubs”
  -  Announcements
  -  Tasks/assignments
- Discover Page
  -  Search club DB
  -  Interests quiz
  -  Club recommendations (clubs assigned interests, match user interests to club interests to determine best fits)
  -  Gemini API integration
- Club Pages
  -  Member counts
  -  Leadership and roles
  -  Description
  -  Contact forms
- Profile Page
  -  Roles/achievements
  -  UI/profile customization
  -  User info, stats
- Chatrooms
  -  Per-club
  -  Gemini API integration (chatbots)
  -  Translate API integration

### Group 1: Club Management

| Name   | Link | Assignments                                                                                 |
|--------|------|---------------------------------------------------------------------------------------------|
| Aarav  |   https://github.com/Aarav445/Aarav_2025   | Join/leave clubs and cache clubs on a per-user basis, user roles in each club, club page UI and functionality with CSS and JS, Cache number of members on a per-club basis                      |
| Gyutae |   https://github.com/GyutaeKim1/Gyutae_2025   | Add new clubs, chatrooms dynamic on per-club basis, draw.io flowchart for full stack site functionality                      |
| Jonah (assistant scrum)   |   https://github.com/luojonah/jonahluo_student2025   | User authentication and profile data, profile page functionality and UI customization, overall UI functionality with CSS and JS,  club page functionality (backend) on per-club basis, dynamic .                 |

### Group 2: UI, User Management

| Name   | Link | Assignments                                                                                 |
|--------|------|---------------------------------------------------------------------------------------------|
| Ansh (scrum master)  |   https://github.com/magic005/AnshCSP   | Discover page UI functionality with CSS and JS, user interests cached on per-user basis, match users to clubs, home page UI and functionality with CSS and JS, Kanban board                 |
| Ethan |   https://github.com/EthanZ123/ethan_2025   | API integrations for recommendations and chatting, chatrooms pages UI and functionality with CSS and JS                               |

***Align with CPT requirements***

## Tasks
- [x] Ideation, determine features and potential implementations, delegate, create kanban board
- [x] Initial set up – create and initialize frontend and backend repositories
- [ ] Add pages (minimal functionality, proof of concept)
- [ ] Backend functionality (per-user and per-club databases for multiple parameters)
- [ ] UI design finalization and implementation, JS and CSS functionality per-page
- [ ] Frontend integration – “fetch” logics, API integration, frontend functionality
- [ ] Testing, final changes

**Comment by jm1021** [comment]
Clubs is a great topic.  You have some things that are starting on the idea.

In addition to what you share. There are needs for tracking meetings, communicating with sponsor and ASB.  This is to report on monthly meetings and have sponsor sign off.

Regarding discovery, this could be bi-directional.  For instance some clubs start to dwindle in membership and there could be need to rush clubs by leadership finding and recruiting people in database.  People could add themself to database and do a survey that might aid people to find people that are looking are unsure about what to join.

CPT requirements are not discussed.

.9 for now, but ideation should be more develped.
